### ISSUE TITLE
Ambiguous use of 'allKeys' error in OS X, Xcode 7.0.1 

### ISSUE THREAD

**Issue by symonty** [dankogai/swift-json#27] opened 2015-09-30 07:24 UTC
json.swift:363:26: Ambiguous use of 'allKeys'
json.swift:360:17: Ambiguous use of 'allKeys'

Just migrating code to Xcode 7.0.1 and Swift 2.0 getting a weird error I don't see on iOS but do on OS X?

**Comment by dankogai** [comment] 2015-09-30 07:44
Try:
* getting a fresh copy via `git clone`
* clean the project (cmd+shift+K)

**Comment by symonty** [comment] 2015-09-30 07:51
Tired no luck, will ask one of my fellow devs to try tomrrow too.

**Comment by symonty** [comment] 2015-09-30 17:39
Must be an apple issue, run the project from GIT and it works fine, just when the json.swift is in my project it complains, no idea why or what ambiguous even means

**Comment by symonty** [comment] 2015-10-24 04:25
Ok if i copy and paste the source it fails, i have a cocoa and a cocoa touch project in one it fails and in the other it does not.
![screen shot 2015-10-23 at 9 23 30 pm](https://cloud.githubusercontent.com/assets/1103948/10708845/542dbc12-79cc-11e5-8622-41e040ea57d0.png)
Screenshot shown in playground.
I changed the code to this, and now it works ( i think )
    // gives all keys content in JSON object.
    public var allKeys:JSON{
        if(Array(self._value.allKeys) == []) {
            return JSON([])
        }
        return JSON(Array(self._value.allKeys))
    }

**Comment by hippymulehead** [comment] 2015-10-27 19:27
This seems to happen when you don't use this as a framework (where it only imports Foundation) and you have Cocoa in your project.  .allKeys seems to be defined differently between Foundation and Cocoa.  Anyway, that's how I reproduce the error here...

**Comment by hippymulehead** [comment] 2015-10-27 20:20
Changing the _value.allKeys to _value.allObjects seems to fix the issue here.

**Comment by dankogai** [comment] 2015-11-02 17:19
Fixed in https://github.com/dankogai/swift-json/commit/f09a5a00716c4eed4a0af1b98f4df0ca716f8914 exactly as suggested.

**Closed by dankogai** 2015-11-02 17:19 UTC
